// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 3 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int aboutthisprotocol_3 = 3;
	/// <summary>PID: 3 | Type: read</summary>
	public const int aboutthisprotocol = 3;
	/// <summary>PID: 101 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responseadata_101 = 101;
	/// <summary>PID: 101 | Type: read</summary>
	public const int responseadata = 101;
	/// <summary>PID: 200 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responsebkeyfield_200 = 200;
	/// <summary>PID: 200 | Type: read</summary>
	public const int responsebkeyfield = 200;
	/// <summary>PID: 202 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responsebvaluefield_202 = 202;
	/// <summary>PID: 202 | Type: read</summary>
	public const int responsebvaluefield = 202;
	/// <summary>PID: 300 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responseckeyfield_300 = 300;
	/// <summary>PID: 300 | Type: read</summary>
	public const int responseckeyfield = 300;
	/// <summary>PID: 301 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responsecvariabledata_301 = 301;
	/// <summary>PID: 301 | Type: read</summary>
	public const int responsecvariabledata = 301;
	/// <summary>PID: 304 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responsecvariablelengthdatafield_304 = 304;
	/// <summary>PID: 304 | Type: read</summary>
	public const int responsecvariablelengthdatafield = 304;
	/// <summary>PID: 402 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responsedvariablelengthdatafield_402 = 402;
	/// <summary>PID: 402 | Type: read</summary>
	public const int responsedvariablelengthdatafield = 402;
	/// <summary>PID: 500 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responseekeyfield_500 = 500;
	/// <summary>PID: 500 | Type: read</summary>
	public const int responseekeyfield = 500;
	/// <summary>PID: 501 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responseevariabledata_501 = 501;
	/// <summary>PID: 501 | Type: read</summary>
	public const int responseevariabledata = 501;
	/// <summary>PID: 503 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responseelengthfield_503 = 503;
	/// <summary>PID: 503 | Type: read</summary>
	public const int responseelengthfield = 503;
	/// <summary>PID: 504 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responseevariablelengthdatafield_504 = 504;
	/// <summary>PID: 504 | Type: read</summary>
	public const int responseevariablelengthdatafield = 504;
	/// <summary>PID: 603 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responsefvariablelengthdatafield_603 = 603;
	/// <summary>PID: 603 | Type: read</summary>
	public const int responsefvariablelengthdatafield = 603;
	/// <summary>PID: 5000 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int commandastarttime_5000 = 5000;
	/// <summary>PID: 5000 | Type: read</summary>
	public const int commandastarttime = 5000;
	/// <summary>PID: 5001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int commandbstarttime_5001 = 5001;
	/// <summary>PID: 5001 | Type: read</summary>
	public const int commandbstarttime = 5001;
	/// <summary>PID: 5002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int commandcstarttime_5002 = 5002;
	/// <summary>PID: 5002 | Type: read</summary>
	public const int commandcstarttime = 5002;
	/// <summary>PID: 5003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int commanddstarttime_5003 = 5003;
	/// <summary>PID: 5003 | Type: read</summary>
	public const int commanddstarttime = 5003;
	/// <summary>PID: 5004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int commandestarttime_5004 = 5004;
	/// <summary>PID: 5004 | Type: read</summary>
	public const int commandestarttime = 5004;
	/// <summary>PID: 5005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int commandfstarttime_5005 = 5005;
	/// <summary>PID: 5005 | Type: read</summary>
	public const int commandfstarttime = 5005;
	/// <summary>PID: 5100 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responseamatchingduration_5100 = 5100;
	/// <summary>PID: 5100 | Type: read</summary>
	public const int responseamatchingduration = 5100;
	/// <summary>PID: 5101 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responsebmatchingduration_5101 = 5101;
	/// <summary>PID: 5101 | Type: read</summary>
	public const int responsebmatchingduration = 5101;
	/// <summary>PID: 5102 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responsecmatchingduration_5102 = 5102;
	/// <summary>PID: 5102 | Type: read</summary>
	public const int responsecmatchingduration = 5102;
	/// <summary>PID: 5103 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responsedmatchingduration_5103 = 5103;
	/// <summary>PID: 5103 | Type: read</summary>
	public const int responsedmatchingduration = 5103;
	/// <summary>PID: 5104 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responseematchingduration_5104 = 5104;
	/// <summary>PID: 5104 | Type: read</summary>
	public const int responseematchingduration = 5104;
	/// <summary>PID: 5105 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int responsefmatchingduration_5105 = 5105;
	/// <summary>PID: 5105 | Type: read</summary>
	public const int responsefmatchingduration = 5105;
	public class Write
	{
		/// <summary>PID: 20 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int sendcommandabutton_20 = 20;
		/// <summary>PID: 20 | Type: write</summary>
		public const int sendcommandabutton = 20;
		/// <summary>PID: 21 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int sendcommandbbutton_21 = 21;
		/// <summary>PID: 21 | Type: write</summary>
		public const int sendcommandbbutton = 21;
		/// <summary>PID: 22 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int sendcommandcbutton_22 = 22;
		/// <summary>PID: 22 | Type: write</summary>
		public const int sendcommandcbutton = 22;
		/// <summary>PID: 23 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int sendcommanddbutton_23 = 23;
		/// <summary>PID: 23 | Type: write</summary>
		public const int sendcommanddbutton = 23;
		/// <summary>PID: 24 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int sendcommandebutton_24 = 24;
		/// <summary>PID: 24 | Type: write</summary>
		public const int sendcommandebutton = 24;
		/// <summary>PID: 25 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int sendcommandfbutton_25 = 25;
		/// <summary>PID: 25 | Type: write</summary>
		public const int sendcommandfbutton = 25;
	}
}
public class WriteParameters
{
	/// <summary>PID: 20  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandabutton {get { return Protocol.GetParameter(20); }set { Protocol.SetParameter(20, value); }}
	/// <summary>PID: 21  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandbbutton {get { return Protocol.GetParameter(21); }set { Protocol.SetParameter(21, value); }}
	/// <summary>PID: 22  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandcbutton {get { return Protocol.GetParameter(22); }set { Protocol.SetParameter(22, value); }}
	/// <summary>PID: 23  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommanddbutton {get { return Protocol.GetParameter(23); }set { Protocol.SetParameter(23, value); }}
	/// <summary>PID: 24  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandebutton {get { return Protocol.GetParameter(24); }set { Protocol.SetParameter(24, value); }}
	/// <summary>PID: 25  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandfbutton {get { return Protocol.GetParameter(25); }set { Protocol.SetParameter(25, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Aboutthisprotocol_3 { get; set; }
	object Aboutthisprotocol { get; set; }
	object Fillinhelp__fixed { get; set; }
	object Sendcommandabutton_20 { get; set; }
	object Sendcommandabutton { get; set; }
	object Sendcommandbbutton_21 { get; set; }
	object Sendcommandbbutton { get; set; }
	object Sendcommandcbutton_22 { get; set; }
	object Sendcommandcbutton { get; set; }
	object Sendcommanddbutton_23 { get; set; }
	object Sendcommanddbutton { get; set; }
	object Sendcommandebutton_24 { get; set; }
	object Sendcommandebutton { get; set; }
	object Sendcommandfbutton_25 { get; set; }
	object Sendcommandfbutton { get; set; }
	object Commanda__fixed { get; set; }
	object Commandb__fixed { get; set; }
	object Commandc__fixed { get; set; }
	object Commandd__fixed { get; set; }
	object Commande__fixed { get; set; }
	object Commandf__fixed { get; set; }
	object Responseaheader_header { get; set; }
	object Responseadata_101 { get; set; }
	object Responseadata { get; set; }
	object Responseatrailer_trailer { get; set; }
	object Responsebkeyfield_200 { get; set; }
	object Responsebkeyfield { get; set; }
	object Responsebfixedcolon__fixed { get; set; }
	object Responsebvaluefield_202 { get; set; }
	object Responsebvaluefield { get; set; }
	object Responseckeyfield_300 { get; set; }
	object Responseckeyfield { get; set; }
	object Responsecvariabledata_301 { get; set; }
	object Responsecvariabledata { get; set; }
	object Responsecfixedcolon__fixed { get; set; }
	object Responseclengthfield_length { get; set; }
	object Responsecvariablelengthdatafield_304 { get; set; }
	object Responsecvariablelengthdatafield { get; set; }
	object Responsedheader_header { get; set; }
	object Responsedlengthfield_length { get; set; }
	object Responsedvariablelengthdatafield_402 { get; set; }
	object Responsedvariablelengthdatafield { get; set; }
	object Responsedtrailer_trailer { get; set; }
	object Responseekeyfield_500 { get; set; }
	object Responseekeyfield { get; set; }
	object Responseevariabledata_501 { get; set; }
	object Responseevariabledata { get; set; }
	object Responseefixedcolon__fixed { get; set; }
	object Responseelengthfield_503 { get; set; }
	object Responseelengthfield { get; set; }
	object Responseevariablelengthdatafield_504 { get; set; }
	object Responseevariablelengthdatafield { get; set; }
	object Responsefkeyfield_header { get; set; }
	object Responseflengthfield_length { get; set; }
	object Responseffixedcolon_trailer { get; set; }
	object Responsefvariablelengthdatafield_603 { get; set; }
	object Responsefvariablelengthdatafield { get; set; }
	object Responseffixeddash__fixed { get; set; }
	object Commandastarttime_5000 { get; set; }
	object Commandastarttime { get; set; }
	object Commandbstarttime_5001 { get; set; }
	object Commandbstarttime { get; set; }
	object Commandcstarttime_5002 { get; set; }
	object Commandcstarttime { get; set; }
	object Commanddstarttime_5003 { get; set; }
	object Commanddstarttime { get; set; }
	object Commandestarttime_5004 { get; set; }
	object Commandestarttime { get; set; }
	object Commandfstarttime_5005 { get; set; }
	object Commandfstarttime { get; set; }
	object Responseamatchingduration_5100 { get; set; }
	object Responseamatchingduration { get; set; }
	object Responsebmatchingduration_5101 { get; set; }
	object Responsebmatchingduration { get; set; }
	object Responsecmatchingduration_5102 { get; set; }
	object Responsecmatchingduration { get; set; }
	object Responsedmatchingduration_5103 { get; set; }
	object Responsedmatchingduration { get; set; }
	object Responseematchingduration_5104 { get; set; }
	object Responseematchingduration { get; set; }
	object Responsefmatchingduration_5105 { get; set; }
	object Responsefmatchingduration { get; set; }
	object Afterresponsea_dummy { get; set; }
	object Afterresponseb_dummy { get; set; }
	object Afterresponsec_dummy { get; set; }
	object Afterresponsed_dummy { get; set; }
	object Afterresponsee_dummy { get; set; }
	object Afterresponsef_dummy { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 3  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Aboutthisprotocol_3 {get { return GetParameter(3); }set { SetParameter(3, value); }}
	/// <summary>PID: 3  | Type: read</summary>
	public System.Object Aboutthisprotocol {get { return GetParameter(3); }set { SetParameter(3, value); }}
	/// <summary>PID: 4  | Type: fixed</summary>
	public System.Object Fillinhelp__fixed {get { return GetParameter(4); }set { SetParameter(4, value); }}
	/// <summary>PID: 20  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandabutton_20 {get { return GetParameter(20); }set { SetParameter(20, value); }}
	/// <summary>PID: 20  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandabutton {get { return Write.Sendcommandabutton; }set { Write.Sendcommandabutton = value; }}
	/// <summary>PID: 21  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandbbutton_21 {get { return GetParameter(21); }set { SetParameter(21, value); }}
	/// <summary>PID: 21  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandbbutton {get { return Write.Sendcommandbbutton; }set { Write.Sendcommandbbutton = value; }}
	/// <summary>PID: 22  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandcbutton_22 {get { return GetParameter(22); }set { SetParameter(22, value); }}
	/// <summary>PID: 22  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandcbutton {get { return Write.Sendcommandcbutton; }set { Write.Sendcommandcbutton = value; }}
	/// <summary>PID: 23  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommanddbutton_23 {get { return GetParameter(23); }set { SetParameter(23, value); }}
	/// <summary>PID: 23  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommanddbutton {get { return Write.Sendcommanddbutton; }set { Write.Sendcommanddbutton = value; }}
	/// <summary>PID: 24  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandebutton_24 {get { return GetParameter(24); }set { SetParameter(24, value); }}
	/// <summary>PID: 24  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandebutton {get { return Write.Sendcommandebutton; }set { Write.Sendcommandebutton = value; }}
	/// <summary>PID: 25  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandfbutton_25 {get { return GetParameter(25); }set { SetParameter(25, value); }}
	/// <summary>PID: 25  | Type: write | DISCREETS: Send = 1</summary>
	public System.Object Sendcommandfbutton {get { return Write.Sendcommandfbutton; }set { Write.Sendcommandfbutton = value; }}
	/// <summary>PID: 50  | Type: fixed</summary>
	public System.Object Commanda__fixed {get { return GetParameter(50); }set { SetParameter(50, value); }}
	/// <summary>PID: 51  | Type: fixed</summary>
	public System.Object Commandb__fixed {get { return GetParameter(51); }set { SetParameter(51, value); }}
	/// <summary>PID: 52  | Type: fixed</summary>
	public System.Object Commandc__fixed {get { return GetParameter(52); }set { SetParameter(52, value); }}
	/// <summary>PID: 53  | Type: fixed</summary>
	public System.Object Commandd__fixed {get { return GetParameter(53); }set { SetParameter(53, value); }}
	/// <summary>PID: 54  | Type: fixed</summary>
	public System.Object Commande__fixed {get { return GetParameter(54); }set { SetParameter(54, value); }}
	/// <summary>PID: 55  | Type: fixed</summary>
	public System.Object Commandf__fixed {get { return GetParameter(55); }set { SetParameter(55, value); }}
	/// <summary>PID: 100  | Type: header</summary>
	public System.Object Responseaheader_header {get { return GetParameter(100); }set { SetParameter(100, value); }}
	/// <summary>PID: 101  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responseadata_101 {get { return GetParameter(101); }set { SetParameter(101, value); }}
	/// <summary>PID: 101  | Type: read</summary>
	public System.Object Responseadata {get { return GetParameter(101); }set { SetParameter(101, value); }}
	/// <summary>PID: 102  | Type: trailer</summary>
	public System.Object Responseatrailer_trailer {get { return GetParameter(102); }set { SetParameter(102, value); }}
	/// <summary>PID: 200  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responsebkeyfield_200 {get { return GetParameter(200); }set { SetParameter(200, value); }}
	/// <summary>PID: 200  | Type: read</summary>
	public System.Object Responsebkeyfield {get { return GetParameter(200); }set { SetParameter(200, value); }}
	/// <summary>PID: 201  | Type: fixed</summary>
	public System.Object Responsebfixedcolon__fixed {get { return GetParameter(201); }set { SetParameter(201, value); }}
	/// <summary>PID: 202  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responsebvaluefield_202 {get { return GetParameter(202); }set { SetParameter(202, value); }}
	/// <summary>PID: 202  | Type: read</summary>
	public System.Object Responsebvaluefield {get { return GetParameter(202); }set { SetParameter(202, value); }}
	/// <summary>PID: 300  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responseckeyfield_300 {get { return GetParameter(300); }set { SetParameter(300, value); }}
	/// <summary>PID: 300  | Type: read</summary>
	public System.Object Responseckeyfield {get { return GetParameter(300); }set { SetParameter(300, value); }}
	/// <summary>PID: 301  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responsecvariabledata_301 {get { return GetParameter(301); }set { SetParameter(301, value); }}
	/// <summary>PID: 301  | Type: read</summary>
	public System.Object Responsecvariabledata {get { return GetParameter(301); }set { SetParameter(301, value); }}
	/// <summary>PID: 302  | Type: fixed</summary>
	public System.Object Responsecfixedcolon__fixed {get { return GetParameter(302); }set { SetParameter(302, value); }}
	/// <summary>PID: 303  | Type: length</summary>
	public System.Object Responseclengthfield_length {get { return GetParameter(303); }set { SetParameter(303, value); }}
	/// <summary>PID: 304  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responsecvariablelengthdatafield_304 {get { return GetParameter(304); }set { SetParameter(304, value); }}
	/// <summary>PID: 304  | Type: read</summary>
	public System.Object Responsecvariablelengthdatafield {get { return GetParameter(304); }set { SetParameter(304, value); }}
	/// <summary>PID: 400  | Type: header</summary>
	public System.Object Responsedheader_header {get { return GetParameter(400); }set { SetParameter(400, value); }}
	/// <summary>PID: 401  | Type: length</summary>
	public System.Object Responsedlengthfield_length {get { return GetParameter(401); }set { SetParameter(401, value); }}
	/// <summary>PID: 402  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responsedvariablelengthdatafield_402 {get { return GetParameter(402); }set { SetParameter(402, value); }}
	/// <summary>PID: 402  | Type: read</summary>
	public System.Object Responsedvariablelengthdatafield {get { return GetParameter(402); }set { SetParameter(402, value); }}
	/// <summary>PID: 403  | Type: trailer</summary>
	public System.Object Responsedtrailer_trailer {get { return GetParameter(403); }set { SetParameter(403, value); }}
	/// <summary>PID: 500  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responseekeyfield_500 {get { return GetParameter(500); }set { SetParameter(500, value); }}
	/// <summary>PID: 500  | Type: read</summary>
	public System.Object Responseekeyfield {get { return GetParameter(500); }set { SetParameter(500, value); }}
	/// <summary>PID: 501  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responseevariabledata_501 {get { return GetParameter(501); }set { SetParameter(501, value); }}
	/// <summary>PID: 501  | Type: read</summary>
	public System.Object Responseevariabledata {get { return GetParameter(501); }set { SetParameter(501, value); }}
	/// <summary>PID: 502  | Type: fixed</summary>
	public System.Object Responseefixedcolon__fixed {get { return GetParameter(502); }set { SetParameter(502, value); }}
	/// <summary>PID: 503  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responseelengthfield_503 {get { return GetParameter(503); }set { SetParameter(503, value); }}
	/// <summary>PID: 503  | Type: read</summary>
	public System.Object Responseelengthfield {get { return GetParameter(503); }set { SetParameter(503, value); }}
	/// <summary>PID: 504  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responseevariablelengthdatafield_504 {get { return GetParameter(504); }set { SetParameter(504, value); }}
	/// <summary>PID: 504  | Type: read</summary>
	public System.Object Responseevariablelengthdatafield {get { return GetParameter(504); }set { SetParameter(504, value); }}
	/// <summary>PID: 600  | Type: header</summary>
	public System.Object Responsefkeyfield_header {get { return GetParameter(600); }set { SetParameter(600, value); }}
	/// <summary>PID: 601  | Type: length</summary>
	public System.Object Responseflengthfield_length {get { return GetParameter(601); }set { SetParameter(601, value); }}
	/// <summary>PID: 602  | Type: trailer</summary>
	public System.Object Responseffixedcolon_trailer {get { return GetParameter(602); }set { SetParameter(602, value); }}
	/// <summary>PID: 603  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responsefvariablelengthdatafield_603 {get { return GetParameter(603); }set { SetParameter(603, value); }}
	/// <summary>PID: 603  | Type: read</summary>
	public System.Object Responsefvariablelengthdatafield {get { return GetParameter(603); }set { SetParameter(603, value); }}
	/// <summary>PID: 610  | Type: fixed</summary>
	public System.Object Responseffixeddash__fixed {get { return GetParameter(610); }set { SetParameter(610, value); }}
	/// <summary>PID: 5000  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Commandastarttime_5000 {get { return GetParameter(5000); }set { SetParameter(5000, value); }}
	/// <summary>PID: 5000  | Type: read</summary>
	public System.Object Commandastarttime {get { return GetParameter(5000); }set { SetParameter(5000, value); }}
	/// <summary>PID: 5001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Commandbstarttime_5001 {get { return GetParameter(5001); }set { SetParameter(5001, value); }}
	/// <summary>PID: 5001  | Type: read</summary>
	public System.Object Commandbstarttime {get { return GetParameter(5001); }set { SetParameter(5001, value); }}
	/// <summary>PID: 5002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Commandcstarttime_5002 {get { return GetParameter(5002); }set { SetParameter(5002, value); }}
	/// <summary>PID: 5002  | Type: read</summary>
	public System.Object Commandcstarttime {get { return GetParameter(5002); }set { SetParameter(5002, value); }}
	/// <summary>PID: 5003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Commanddstarttime_5003 {get { return GetParameter(5003); }set { SetParameter(5003, value); }}
	/// <summary>PID: 5003  | Type: read</summary>
	public System.Object Commanddstarttime {get { return GetParameter(5003); }set { SetParameter(5003, value); }}
	/// <summary>PID: 5004  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Commandestarttime_5004 {get { return GetParameter(5004); }set { SetParameter(5004, value); }}
	/// <summary>PID: 5004  | Type: read</summary>
	public System.Object Commandestarttime {get { return GetParameter(5004); }set { SetParameter(5004, value); }}
	/// <summary>PID: 5005  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Commandfstarttime_5005 {get { return GetParameter(5005); }set { SetParameter(5005, value); }}
	/// <summary>PID: 5005  | Type: read</summary>
	public System.Object Commandfstarttime {get { return GetParameter(5005); }set { SetParameter(5005, value); }}
	/// <summary>PID: 5100  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responseamatchingduration_5100 {get { return GetParameter(5100); }set { SetParameter(5100, value); }}
	/// <summary>PID: 5100  | Type: read</summary>
	public System.Object Responseamatchingduration {get { return GetParameter(5100); }set { SetParameter(5100, value); }}
	/// <summary>PID: 5101  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responsebmatchingduration_5101 {get { return GetParameter(5101); }set { SetParameter(5101, value); }}
	/// <summary>PID: 5101  | Type: read</summary>
	public System.Object Responsebmatchingduration {get { return GetParameter(5101); }set { SetParameter(5101, value); }}
	/// <summary>PID: 5102  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responsecmatchingduration_5102 {get { return GetParameter(5102); }set { SetParameter(5102, value); }}
	/// <summary>PID: 5102  | Type: read</summary>
	public System.Object Responsecmatchingduration {get { return GetParameter(5102); }set { SetParameter(5102, value); }}
	/// <summary>PID: 5103  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responsedmatchingduration_5103 {get { return GetParameter(5103); }set { SetParameter(5103, value); }}
	/// <summary>PID: 5103  | Type: read</summary>
	public System.Object Responsedmatchingduration {get { return GetParameter(5103); }set { SetParameter(5103, value); }}
	/// <summary>PID: 5104  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responseematchingduration_5104 {get { return GetParameter(5104); }set { SetParameter(5104, value); }}
	/// <summary>PID: 5104  | Type: read</summary>
	public System.Object Responseematchingduration {get { return GetParameter(5104); }set { SetParameter(5104, value); }}
	/// <summary>PID: 5105  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Responsefmatchingduration_5105 {get { return GetParameter(5105); }set { SetParameter(5105, value); }}
	/// <summary>PID: 5105  | Type: read</summary>
	public System.Object Responsefmatchingduration {get { return GetParameter(5105); }set { SetParameter(5105, value); }}
	/// <summary>PID: 10000  | Type: dummy</summary>
	public System.Object Afterresponsea_dummy {get { return GetParameter(10000); }set { SetParameter(10000, value); }}
	/// <summary>PID: 10001  | Type: dummy</summary>
	public System.Object Afterresponseb_dummy {get { return GetParameter(10001); }set { SetParameter(10001, value); }}
	/// <summary>PID: 10002  | Type: dummy</summary>
	public System.Object Afterresponsec_dummy {get { return GetParameter(10002); }set { SetParameter(10002, value); }}
	/// <summary>PID: 10003  | Type: dummy</summary>
	public System.Object Afterresponsed_dummy {get { return GetParameter(10003); }set { SetParameter(10003, value); }}
	/// <summary>PID: 10004  | Type: dummy</summary>
	public System.Object Afterresponsee_dummy {get { return GetParameter(10004); }set { SetParameter(10004, value); }}
	/// <summary>PID: 10005  | Type: dummy</summary>
	public System.Object Afterresponsef_dummy {get { return GetParameter(10005); }set { SetParameter(10005, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
